export default {
  Inter_400Regular: require('../assets/fonts/Inter_400Regular.ttf'),
  Inter_500Medium: require('../assets/fonts/Inter_500Medium.ttf'),
  Inter_600SemiBold: require('../assets/fonts/Inter_600SemiBold.ttf'),
  Inter_700Bold: require('../assets/fonts/Inter_700Bold.ttf'),
  Inter_800ExtraBold: require('../assets/fonts/Inter_800ExtraBold.ttf'),
  Inter_300Light: require('../assets/fonts/Inter_300Light.ttf'),
  OpenSans_500Medium: require('../assets/fonts/OpenSans_500Medium.ttf'),
  OpenSans_600SemiBold: require('../assets/fonts/OpenSans_600SemiBold.ttf'),
  Poppins_500Medium: require('../assets/fonts/Poppins_500Medium.ttf'),
  Poppins_600SemiBold: require('../assets/fonts/Poppins_600SemiBold.ttf'),
  Poppins_400Regular: require('../assets/fonts/Poppins_400Regular.ttf'),
  Rubik_400Regular: require('../assets/fonts/Rubik_400Regular.ttf'),
  Rubik_500Medium: require('../assets/fonts/Rubik_500Medium.ttf'),
};
