export default {
  ObGoogle: require('../assets/images/ObGoogle.png'),
  ObApple: require('../assets/images/ObApple.png'),
  Onboarding2: require('../assets/images/Onboarding2.png'),
  Ob2Button: require('../assets/images/Ob2Button.png'),
  BookbitGradient: require('../assets/images/BookbitGradient.png'),
  suno: require('../assets/images/Suno.png'),
  whitelogo: require('../assets/images/WhiteLogo.svg'),
  applogo: require('../assets/images/AppLogo.png'),
  IconSMS: require('../assets/images/IconSMS.png'),
  ViaEmail: require('../assets/images/ViaEmail.png'),
  forgotpassword: require('../assets/images/Forgotpassword.png'),
  logologin: require('../assets/images/LogoLogin.png'),
  forgotpassword2: require('../assets/images/ForgotPassword2.png'),
  'sunologo(2)': require('../assets/images/SunoLogo(2).png'),
  sunopurplebannerlogo: require('../assets/images/SunoPurpleBannerLogo.png'),
  Avatar: require('../assets/images/Avatar.jpeg'),
  Sub4: require('../assets/images/Sub4.png'),
  Notifications: require('../assets/images/Notifications.png'),
  GoliveSI: require('../assets/images/GoliveSI.png'),
  UserImage: require('../assets/images/UserImage.png'),
  HomeBG: require('../assets/images/HomeBG.png'),
  PortraitSmilingAfroAmericanSportsManStretchingHisMuscularArmsBeforeWorkoutBySeaUsingMusicAppHisSmartphone1: require('../assets/images/PortraitSmilingAfroAmericanSportsManStretchingHisMuscularArmsBeforeWorkoutBySeaUsingMusicAppHisSmartphone1.png'),
  Doctor: require('../assets/images/Doctor.png'),
  Filter: require('../assets/images/Filter.png'),
  Progress: require('../assets/images/Progress.png'),
  Banner: require('../assets/images/Banner.png'),
  EditSquare: require('../assets/images/EditSquare.png'),
  IconLock: require('../assets/images/IconLock.png'),
  Unlock: require('../assets/images/Unlock.png'),
  ShieldDone: require('../assets/images/ShieldDone.png'),
  Globe: require('../assets/images/Globe.png'),
  Layer2: require('../assets/images/Layer2.png'),
  Shield: require('../assets/images/Shield.png'),
  Question: require('../assets/images/Question.png'),
  Activity: require('../assets/images/Activity.png'),
  resetpasswordamico: require('../assets/images/ResetPasswordAmico.png'),
  userlogo: require('../assets/images/Userlogo.png'),
  sunowhitelogo: require('../assets/images/Sunowhitelogo.png'),
  chat:require('../assets/images/chat.png'),
  
};
